name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            file: "*.zip"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build GoVarnam
        run: |
          cd ../
          git clone https://github.com/varnamproject/govarnam.git govarnam
          cd govarnam
          make
          sudo make install

      - name: Build GoVarnam-IBus Engine
        run: |
          sudo apt install libgtk-3-dev libcairo2-dev libglib2.0-dev
          make ubuntu-14
          make release

      - name: Upload Release Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.file }}
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
